### PR TITLE
fix: guard against missing `isSampled` attribute

### PR DESCRIPTION
**Pull request by SimenB**
## Why

I'm not sure why, but we sometimes get an error from Faro with `cannot read property 'toString' of undefined`. It doesn't happen with all users, only some

## What

Makes sure there's a valid value on which to call `toString`

## Checklist

- [ ] Tests added
- [x] Changelog updated
- [ ] Documentation updated

### CODE REVIEW

**Review by codecapitano — APPROVED** [review]
Awesome, thanks a lot Simen. 
We'll release the fix tomorrow

**Review by codecapitano — CHANGES_REQUESTED** [review]
Missed this one: Please update the CHANGELOG.

**Comment by SimenB** [comment]
Done (from mobile, so hopefully not too wonky)

**Review by codecapitano — APPROVED** [review]
LGTM

**Pull request merged**
